on: push
name: on push
jobs:
  job1:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    outputs:
      output1: ${{ steps.read_file_name.outputs.files_info }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6
      - id: print_log
        run: echo "I'm running on ${{ steps.changed-files.outputs.all_changed_files }}"
      - id: read_file_name
        run: |
            changed_files=test_99
            echo "::set-output name=files_info::WORLD"
  job2:
    needs: job1
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: python validations
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: echo "received files ${{needs.job1.outputs.files_info}}"

