on: push
name: all files check
jobs:
  job1:
    build:
      name:PythonAllFiles
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: run validation on files
        run: python .github/workflows/validate_all_files.py
